package presets

import "github.com/nerifect/nerifect-cli/internal/store"

func init() {
	register(Preset{
		Name:           "CIS Docker Benchmark",
		Slug:           "cis-docker",
		Description:    "CIS Docker Benchmark - pattern-based checks for Dockerfile and container security best practices",
		Category:       store.PolicyCategorySecurity,
		Severity:       store.SeverityHigh,
		RegulationType: "SECURITY",
		Rules: []Rule{
			{
				RuleID:          "CIS-DOCKER-1",
				Title:           "Container running as root",
				Description:     "Dockerfile explicitly sets USER to root. Containers should run as non-root for least privilege.",
				Severity:        "HIGH",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^USER\s+root\s*$`,
				Recommendations: []string{"Create a non-root user and set USER to that user in the Dockerfile."},
				ClauseReference: "CIS 4.1",
			},
			{
				RuleID:          "CIS-DOCKER-2",
				Title:           "Using latest tag in base image",
				Description:     "FROM directive uses the 'latest' tag which is mutable and may introduce unexpected changes.",
				Severity:        "MEDIUM",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^FROM\s+\S+:latest`,
				Recommendations: []string{"Pin base images to a specific version or digest for reproducible builds."},
				ClauseReference: "CIS 4.2",
			},
			{
				RuleID:          "CIS-DOCKER-3",
				Title:           "Secrets exposed in ENV directive",
				Description:     "ENV directives containing password, secret, or key values embed secrets in the image layer.",
				Severity:        "CRITICAL",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^ENV\s+\S*(PASSWORD|SECRET|KEY|TOKEN|CREDENTIAL)\S*\s*=\s*\S+`,
				Recommendations: []string{"Use Docker secrets, build args with --secret, or runtime environment variables instead of ENV for secrets."},
				ClauseReference: "CIS 4.3",
			},
			{
				RuleID:          "CIS-DOCKER-4",
				Title:           "Using ADD instead of COPY",
				Description:     "ADD has extra functionality (URL fetch, tar extraction) that can introduce unexpected behavior. COPY is more explicit.",
				Severity:        "LOW",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^ADD\s+`,
				Recommendations: []string{"Use COPY instead of ADD unless you specifically need URL fetching or tar extraction."},
				ClauseReference: "CIS 4.9",
			},
			{
				RuleID:          "CIS-DOCKER-5",
				Title:           "Missing HEALTHCHECK directive",
				Description:     "No HEALTHCHECK instruction in Dockerfile. Health checks enable container orchestrators to detect unhealthy containers.",
				Severity:        "LOW",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^HEALTHCHECK\s+NONE`,
				Recommendations: []string{"Add a HEALTHCHECK instruction to enable container health monitoring."},
				ClauseReference: "CIS 4.6",
			},
			{
				RuleID:          "CIS-DOCKER-6",
				Title:           "Privileged port exposure",
				Description:     "Exposing ports below 1024 requires elevated privileges.",
				Severity:        "MEDIUM",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^EXPOSE\s+([1-9]|[1-9]\d|[1-9]\d{2}|10[0-1]\d|102[0-3])\b`,
				Recommendations: []string{"Use ports above 1024 and map them in your orchestrator if needed."},
				ClauseReference: "CIS 4.5",
			},
			{
				RuleID:          "CIS-DOCKER-7",
				Title:           "Using sudo in Dockerfile",
				Description:     "Using sudo in RUN commands is error-prone and often unnecessary in container builds.",
				Severity:        "MEDIUM",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^RUN\s+.*\bsudo\b`,
				Recommendations: []string{"Run commands as root during build (before USER) and switch to non-root user after."},
				ClauseReference: "CIS 4.1",
			},
			{
				RuleID:          "CIS-DOCKER-8",
				Title:           "apt-get without --no-install-recommends",
				Description:     "Installing packages without --no-install-recommends pulls unnecessary dependencies increasing attack surface.",
				Severity:        "LOW",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)^RUN\s+.*apt-get\s+install(?!.*--no-install-recommends)`,
				Recommendations: []string{"Use 'apt-get install --no-install-recommends' to minimize installed packages."},
				ClauseReference: "CIS 4.9",
			},
			{
				RuleID:          "CIS-DOCKER-9",
				Title:           "curl or wget piped to shell",
				Description:     "Piping downloaded scripts directly to a shell is risky as content may be tampered with.",
				Severity:        "HIGH",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?im)(curl|wget)\s+.*\|\s*(sh|bash|zsh)`,
				Recommendations: []string{"Download scripts to a file, verify their checksum, then execute them."},
				ClauseReference: "CIS 4.9",
			},
			{
				RuleID:          "CIS-DOCKER-10",
				Title:           "Missing Dockerfile",
				Description:     "No Dockerfile found. If this is a containerized application, a Dockerfile should be present.",
				Severity:        "INFO",
				Category:        "CONTAINER_SECURITY",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:Dockerfile",
				Recommendations: []string{"Add a Dockerfile if this application is intended to be containerized."},
				ClauseReference: "CIS 4.0",
			},
		},
	})
}
