package presets

import "github.com/nerifect/nerifect-cli/internal/store"

func init() {
	register(Preset{
		Name:           "GDPR Data Protection Basic",
		Slug:           "gdpr-basic",
		Description:    "GDPR - basic pattern-based checks for personal data protection and privacy compliance",
		Category:       store.PolicyCategoryCompliance,
		Severity:       store.SeverityHigh,
		RegulationType: "REGULATION",
		Rules: []Rule{
			{
				RuleID:          "GDPR-A5-1",
				Title:           "PII logged in application output",
				Description:     "Personal identifiable information (email, SSN, phone) found in logging statements violates data minimization principles.",
				Severity:        "HIGH",
				Category:        "DATA_PROTECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(log|logger|console|print)\s*[\.(]\s*(info|debug|warn|error|log|print|println)?\s*\(?\s*.*\b(email|ssn|social.security|phone.number|date.of.birth|passport|national.id)\b`,
				Recommendations: []string{"Redact or mask PII before logging. Use structured logging with field-level filtering."},
				ClauseReference: "Article 5(1)(c) Data Minimization",
			},
			{
				RuleID:          "GDPR-A5-2",
				Title:           "Hardcoded personal data in source code",
				Description:     "Personal data hardcoded in source code violates data protection by design.",
				Severity:        "HIGH",
				Category:        "DATA_PROTECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(email|user_email)\s*[:=]\s*["'][a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}["']`,
				Recommendations: []string{"Remove hardcoded personal data from source code. Use test data generators for development."},
				ClauseReference: "Article 5(1)(f) Integrity and Confidentiality",
			},
			{
				RuleID:          "GDPR-A25-1",
				Title:           "Missing data encryption at rest",
				Description:     "Storing sensitive data without encryption violates data protection by design and by default.",
				Severity:        "HIGH",
				Category:        "DATA_PROTECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(write|save|store|insert|put)\s*\(?\s*.*\b(personal.data|user.data|pii|sensitive)\b.*(?!.*encrypt)`,
				Recommendations: []string{"Encrypt personal data at rest using AES-256 or equivalent."},
				ClauseReference: "Article 25 Data Protection by Design",
			},
			{
				RuleID:          "GDPR-A30-1",
				Title:           "Missing PRIVACY or data processing documentation",
				Description:     "No privacy policy or data processing documentation found in the repository.",
				Severity:        "MEDIUM",
				Category:        "DOCUMENTATION",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:PRIVACY*",
				Recommendations: []string{"Add a PRIVACY.md or privacy policy documenting data processing activities per Article 30."},
				ClauseReference: "Article 30 Records of Processing Activities",
			},
			{
				RuleID:          "GDPR-A32-1",
				Title:           "Disabled or weak encryption",
				Description:     "Disabled encryption or use of weak algorithms violates technical security measures.",
				Severity:        "CRITICAL",
				Category:        "SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(DES|RC4|ECB|encrypt\s*[:=]\s*(false|no|off|disabled)|SSLv[23]|TLSv1\.0)`,
				Recommendations: []string{"Use modern encryption standards: AES-256-GCM, TLS 1.2+. Disable weak algorithms."},
				ClauseReference: "Article 32 Security of Processing",
			},
			{
				RuleID:          "GDPR-A17-1",
				Title:           "No data deletion mechanism",
				Description:     "Code patterns suggesting data is stored without a deletion or retention mechanism.",
				Severity:        "MEDIUM",
				Category:        "DATA_RIGHTS",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(retention|ttl|expir|purge|delete.?old|cleanup|data.?retention)\s*[:=]\s*(0|false|none|disabled|never)`,
				Recommendations: []string{"Implement data retention policies with automated cleanup for GDPR right to erasure compliance."},
				ClauseReference: "Article 17 Right to Erasure",
			},
			{
				RuleID:          "GDPR-A7-1",
				Title:           "Missing consent mechanism",
				Description:     "Data collection without consent tracking mechanisms may violate lawful processing requirements.",
				Severity:        "MEDIUM",
				Category:        "CONSENT",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(collect|gather|track|capture)\s*\(?\s*.*\b(user.?data|personal|email|analytics)\b(?!.*consent)`,
				Recommendations: []string{"Implement consent tracking. Record when and how user consent was obtained for each data processing purpose."},
				ClauseReference: "Article 7 Conditions for Consent",
			},
			{
				RuleID:          "GDPR-A33-1",
				Title:           "Missing data breach notification mechanism",
				Description:     "No evidence of breach notification or incident response mechanisms.",
				Severity:        "LOW",
				Category:        "INCIDENT_RESPONSE",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:SECURITY*",
				Recommendations: []string{"Add a SECURITY.md file with vulnerability disclosure and incident response procedures."},
				ClauseReference: "Article 33 Notification of Personal Data Breach",
			},
			{
				RuleID:          "GDPR-A5-3",
				Title:           "Unencrypted data transmission",
				Description:     "Transmitting personal data over unencrypted channels violates integrity and confidentiality principles.",
				Severity:        "HIGH",
				Category:        "DATA_PROTECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(ftp|telnet|smtp)://(?!.*ssl|.*tls)`,
				Recommendations: []string{"Use encrypted protocols (SFTP, SMTPS, HTTPS) for all personal data transmission."},
				ClauseReference: "Article 5(1)(f) Integrity and Confidentiality",
			},
			{
				RuleID:          "GDPR-A35-1",
				Title:           "Large-scale data processing without impact assessment",
				Description:     "Code patterns suggesting large-scale data processing that may require a DPIA.",
				Severity:        "LOW",
				Category:        "COMPLIANCE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(bulk.?import|mass.?process|batch.?upload|migrate.?all.?users|process.?all.?records)`,
				Recommendations: []string{"Conduct a Data Protection Impact Assessment (DPIA) for large-scale personal data processing."},
				ClauseReference: "Article 35 Data Protection Impact Assessment",
			},
		},
	})
}
