package presets

import "github.com/nerifect/nerifect-cli/internal/store"

func init() {
	register(Preset{
		Name:           "OWASP Top 10",
		Slug:           "owasp-top-10",
		Description:    "OWASP Top 10 Web Application Security Risks - pattern-based detection for common vulnerabilities",
		Category:       store.PolicyCategorySecurity,
		Severity:       store.SeverityHigh,
		RegulationType: "SECURITY",
		Rules: []Rule{
			{
				RuleID:          "OWASP-A03-1",
				Title:           "Potential SQL injection",
				Description:     "String concatenation or formatting in SQL query functions may allow SQL injection attacks.",
				Severity:        "CRITICAL",
				Category:        "INJECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(execute|query|raw|rawQuery)\s*\(.*(\+\s*["']|%s|\$\{|\bformat\b)`,
				Recommendations: []string{"Use parameterized queries or prepared statements instead of string concatenation."},
				ClauseReference: "A03:2021 Injection",
			},
			{
				RuleID:          "OWASP-A03-2",
				Title:           "Potential XSS via innerHTML",
				Description:     "Direct HTML injection through innerHTML, document.write, or jQuery .html() may allow cross-site scripting.",
				Severity:        "HIGH",
				Category:        "INJECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(innerHTML\s*=|document\.write\s*\(|\.html\s*\()`,
				Recommendations: []string{"Use textContent, createTextNode, or framework-safe rendering instead of innerHTML."},
				ClauseReference: "A03:2021 Injection",
			},
			{
				RuleID:          "OWASP-A03-3",
				Title:           "Potential command injection",
				Description:     "Executing shell commands with string interpolation can lead to command injection.",
				Severity:        "CRITICAL",
				Category:        "INJECTION",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(exec|system|popen|subprocess\.call|child_process\.exec)\s*\(.*(\+\s*["']|\$\{|%s|\bformat\b)`,
				Recommendations: []string{"Use parameterized command execution or allowlists instead of shell interpolation."},
				ClauseReference: "A03:2021 Injection",
			},
			{
				RuleID:          "OWASP-A02-1",
				Title:           "Hardcoded secret or credential",
				Description:     "Passwords, API keys, or tokens hardcoded in source code may be exposed.",
				Severity:        "CRITICAL",
				Category:        "CRYPTO_FAILURE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(password|passwd|secret|api_key|apikey|api_secret|token|auth_token|access_key)\s*[:=]\s*["'][A-Za-z0-9+/=_\-]{8,}`,
				Recommendations: []string{"Store secrets in environment variables or a secrets manager, never in source code."},
				ClauseReference: "A02:2021 Cryptographic Failures",
			},
			{
				RuleID:          "OWASP-A02-2",
				Title:           "Weak hashing algorithm",
				Description:     "MD5 or SHA1 are cryptographically weak and should not be used for security-sensitive operations.",
				Severity:        "HIGH",
				Category:        "CRYPTO_FAILURE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(md5|sha1)\s*[\(.]`,
				Recommendations: []string{"Use SHA-256, bcrypt, scrypt, or Argon2 for cryptographic hashing."},
				ClauseReference: "A02:2021 Cryptographic Failures",
			},
			{
				RuleID:          "OWASP-A02-3",
				Title:           "HTTP URL in configuration",
				Description:     "Unencrypted HTTP URLs in configuration may expose data in transit.",
				Severity:        "MEDIUM",
				Category:        "CRYPTO_FAILURE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)["']http://[^"']*\.(com|org|net|io|dev|app|api)`,
				Recommendations: []string{"Use HTTPS for all external communication to protect data in transit."},
				ClauseReference: "A02:2021 Cryptographic Failures",
			},
			{
				RuleID:          "OWASP-A08-1",
				Title:           "Insecure deserialization",
				Description:     "Unsafe deserialization functions can lead to remote code execution.",
				Severity:        "HIGH",
				Category:        "SOFTWARE_INTEGRITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(pickle\.loads?\s*\(|yaml\.load\s*\(|unserialize\s*\(|Marshal\.load\s*\(|readObject\s*\()`,
				Recommendations: []string{"Use safe deserialization methods (e.g., yaml.safe_load, JSON) and validate input."},
				ClauseReference: "A08:2021 Software and Data Integrity Failures",
			},
			{
				RuleID:          "OWASP-A05-1",
				Title:           "Overly permissive CORS configuration",
				Description:     "Allowing all origins in CORS configuration can expose APIs to cross-origin attacks.",
				Severity:        "MEDIUM",
				Category:        "SECURITY_MISCONFIG",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(Access-Control-Allow-Origin|cors).*['"]\*['"]`,
				Recommendations: []string{"Restrict CORS to specific trusted origins rather than using wildcard '*'."},
				ClauseReference: "A05:2021 Security Misconfiguration",
			},
			{
				RuleID:          "OWASP-A05-2",
				Title:           "Debug mode enabled",
				Description:     "Debug mode left enabled in production can expose sensitive information.",
				Severity:        "MEDIUM",
				Category:        "SECURITY_MISCONFIG",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(DEBUG\s*[:=]\s*True|debug\s*[:=]\s*true|EnableDebug|SetDebug\(true\))`,
				Recommendations: []string{"Ensure debug mode is disabled in production deployments."},
				ClauseReference: "A05:2021 Security Misconfiguration",
			},
			{
				RuleID:          "OWASP-A07-1",
				Title:           "Missing authentication check",
				Description:     "Presence of TODO or FIXME comments related to authentication may indicate incomplete security controls.",
				Severity:        "MEDIUM",
				Category:        "AUTH_FAILURE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(TODO|FIXME|HACK).*\b(auth|login|permission|credential|verify)\b`,
				Recommendations: []string{"Resolve all TODO/FIXME items related to authentication before deployment."},
				ClauseReference: "A07:2021 Identification and Authentication Failures",
			},
			{
				RuleID:          "OWASP-A09-1",
				Title:           "Sensitive data in log output",
				Description:     "Logging sensitive fields like passwords or tokens can lead to data exposure.",
				Severity:        "HIGH",
				Category:        "LOGGING_FAILURE",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(log|logger|console)\s*\.\s*(info|debug|warn|error|print|log)\s*\(.*\b(password|token|secret|ssn|credit.?card)\b`,
				Recommendations: []string{"Redact sensitive fields before logging. Use structured logging with field-level filtering."},
				ClauseReference: "A09:2021 Security Logging and Monitoring Failures",
			},
			{
				RuleID:          "OWASP-A06-1",
				Title:           "Pinned or outdated dependency version",
				Description:     "Very old pinned dependency versions may contain known vulnerabilities.",
				Severity:        "LOW",
				Category:        "VULNERABLE_COMPONENTS",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(==\s*[01]\.\d+\.\d+|"version":\s*"[01]\.\d+)`,
				Recommendations: []string{"Regularly update dependencies and use tools like Dependabot or Renovate."},
				ClauseReference: "A06:2021 Vulnerable and Outdated Components",
			},
			{
				RuleID:          "OWASP-A04-1",
				Title:           "Path traversal risk",
				Description:     "Joining user input with file paths without sanitization can lead to path traversal.",
				Severity:        "HIGH",
				Category:        "INSECURE_DESIGN",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(open|readFile|read_file|send_file)\s*\(.*(\+|join|format|concat).*\b(req|request|params|query|input)\b`,
				Recommendations: []string{"Validate and sanitize file paths. Use allowlists and resolve paths canonically."},
				ClauseReference: "A04:2021 Insecure Design",
			},
			{
				RuleID:          "OWASP-A01-1",
				Title:           "Missing access control file",
				Description:     "No security.txt file found. This file helps security researchers report vulnerabilities.",
				Severity:        "INFO",
				Category:        "ACCESS_CONTROL",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:security.txt",
				Recommendations: []string{"Add a security.txt file (RFC 9116) to document your vulnerability disclosure process."},
				ClauseReference: "A01:2021 Broken Access Control",
			},
		},
	})
}
