package presets

import "github.com/nerifect/nerifect-cli/internal/store"

func init() {
	register(Preset{
		Name:           "SOC2 Type II Basic",
		Slug:           "soc2-basic",
		Description:    "SOC2 Type II - basic pattern-based checks for security, availability, and confidentiality controls",
		Category:       store.PolicyCategoryCompliance,
		Severity:       store.SeverityMedium,
		RegulationType: "COMPLIANCE",
		Rules: []Rule{
			{
				RuleID:          "SOC2-CC6-1",
				Title:           "Hardcoded credentials in source code",
				Description:     "Credentials hardcoded in source code violate SOC2 confidentiality requirements.",
				Severity:        "CRITICAL",
				Category:        "CONFIDENTIALITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(password|passwd|secret|api_key|apikey|private_key)\s*[:=]\s*["'][A-Za-z0-9+/=_\-]{8,}`,
				Recommendations: []string{"Use a secrets manager or environment variables for all credentials."},
				ClauseReference: "CC6.1 Logical Access",
			},
			{
				RuleID:          "SOC2-CC7-1",
				Title:           "Missing error handling",
				Description:     "Empty catch blocks or ignored exceptions can hide security-relevant errors.",
				Severity:        "MEDIUM",
				Category:        "MONITORING",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(catch\s*\([^)]*\)\s*\{\s*\}|except:\s*pass|rescue\s*=>?\s*nil)`,
				Recommendations: []string{"Log or handle all exceptions. Empty catch blocks suppress important error signals."},
				ClauseReference: "CC7.2 System Monitoring",
			},
			{
				RuleID:          "SOC2-CC7-2",
				Title:           "Disabled TLS/SSL verification",
				Description:     "Disabling certificate verification undermines transport security.",
				Severity:        "HIGH",
				Category:        "SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(verify\s*[:=]\s*false|InsecureSkipVerify\s*[:=]\s*true|VERIFY_NONE|verify_ssl\s*[:=]\s*false|rejectUnauthorized\s*[:=]\s*false)`,
				Recommendations: []string{"Always verify TLS certificates in production. Use proper CA certificates."},
				ClauseReference: "CC7.1 Infrastructure Security",
			},
			{
				RuleID:          "SOC2-CC6-2",
				Title:           "Overly permissive file permissions",
				Description:     "Setting world-readable or world-writable permissions (0777, 0666) weakens access controls.",
				Severity:        "MEDIUM",
				Category:        "ACCESS_CONTROL",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(chmod|os\.chmod|FileMode)\s*\(?\s*(0?777|0?666)`,
				Recommendations: []string{"Use least-privilege file permissions. Avoid 777 and 666 modes."},
				ClauseReference: "CC6.1 Logical Access",
			},
			{
				RuleID:          "SOC2-CC7-3",
				Title:           "Security TODO/FIXME remaining",
				Description:     "Unresolved security-related TODO/FIXME comments suggest incomplete security controls.",
				Severity:        "MEDIUM",
				Category:        "SECURITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(TODO|FIXME|HACK|XXX)\s*:?\s*.*(security|vuln|auth|encrypt|permission|access.control)`,
				Recommendations: []string{"Resolve all security-related TODO items before production deployment."},
				ClauseReference: "CC7.1 Infrastructure Security",
			},
			{
				RuleID:          "SOC2-CC8-1",
				Title:           "Temporary or test credentials",
				Description:     "Test or temporary credentials left in code may be exploitable.",
				Severity:        "HIGH",
				Category:        "CONFIDENTIALITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(test_password|temp_key|dummy_secret|changeme|default_password)\s*[:=]`,
				Recommendations: []string{"Remove all test and temporary credentials from production code."},
				ClauseReference: "CC8.1 Change Management",
			},
			{
				RuleID:          "SOC2-CC2-1",
				Title:           "Missing README documentation",
				Description:     "No README file found. Documentation is required for SOC2 operational procedures.",
				Severity:        "LOW",
				Category:        "DOCUMENTATION",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:README*",
				Recommendations: []string{"Add a README file documenting setup, deployment, and operational procedures."},
				ClauseReference: "CC2.1 Communication",
			},
			{
				RuleID:          "SOC2-CC2-2",
				Title:           "Missing LICENSE file",
				Description:     "No LICENSE file found. License documentation supports compliance audits.",
				Severity:        "LOW",
				Category:        "DOCUMENTATION",
				CheckType:       "FILE_PATTERN",
				Pattern:         "missing:LICENSE*",
				Recommendations: []string{"Add a LICENSE file specifying the software license terms."},
				ClauseReference: "CC2.1 Communication",
			},
			{
				RuleID:          "SOC2-CC6-3",
				Title:           "Unencrypted database connection string",
				Description:     "Database connection strings without SSL/TLS parameters may transmit data unencrypted.",
				Severity:        "HIGH",
				Category:        "CONFIDENTIALITY",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(postgresql|mysql|mongodb|redis)://[^?]*["'\s]`,
				Recommendations: []string{"Enable SSL/TLS in database connection strings (e.g., ?sslmode=require)."},
				ClauseReference: "CC6.7 Data Transmission",
			},
			{
				RuleID:          "SOC2-CC6-4",
				Title:           "Disabled authentication",
				Description:     "Code patterns suggesting authentication has been disabled or bypassed.",
				Severity:        "CRITICAL",
				Category:        "ACCESS_CONTROL",
				CheckType:       "CODE_PATTERN",
				Pattern:         `(?i)(auth\s*[:=]\s*false|authenticate\s*[:=]\s*false|NoAuth|skipAuth|disable.?auth)`,
				Recommendations: []string{"Ensure authentication is enabled for all user-facing and API endpoints."},
				ClauseReference: "CC6.1 Logical Access",
			},
		},
	})
}
